export const name = "Community Service";

export const longText = "During these crazy times of social distancing, work from home, and isolation, why not get closer with our neighbors? Everyone has unique skills and services to offer the community and what better way to utilize them than contributing to your neighborhood and offering to help those in need, whether it be phyiscally or mentally. That's why at ShellHacks I decided to make Community Service, a platform for neighbors to connect and find neighbors who are offering to help them with certain services, such as fixing home appliances, picking up groceries for the elderly, or just chatting virtually with those who feel lonely. As a neighborhood, people can help boost moral and decrease stress by continuing their daily routines. Community Service is a web app for neighbors to connect and find neighbors who are offering helpful services. Users can either post services they are offering or browse through services that other people in their neighborhood are offering. If a user would like to ask a neighbor to perform a service, they can contact them with the provided contact information. Since the group membership is moderated by someone in the group, you can ensure that everyone in the group belongs to that neighborhood and would be relatively trustworthy. Also, as a community, you know what the virus prevention requirements are and you are aware of whether the policies are being followed. Thus, this system is much more reliable than having to call a plumber and invite them into your home or physically go to a psychologist when you are depressed. Overall, Community Service promotes interaction and stability in a time of isolation and uncertainty.";

export const shortText = "During these crazy times of social distancing, work from home, and isolation, why not get closer with our neighbors? Everyone has unique skills and services to offer the community...";

export const dates = "September 2020";

export const techUsed = "HTML, CSS, React, Node.js, Express, Postgres, Azure";

export const link = "https://github.com/AmyWeitzman/CommunityService";