export const name = "Ivy";

export const longText = "Meet Ivy, a mental health chatbot to help users find information about mental illnesses, provide resources such as support groups, and suggest activities to better control their mental health. Mental illness is a major issue facing people today, especially during the pandemic. However, while it is a widespread issue, most people with mental illnesses do not seek treatment, often due to the stigma surrounding it. That's why I decided to build Ivy, a mental health chatbot that you can feel comfortable communicating with and discussing your situation knowing that you won't be judged. Ivy can also suggest resources to help you learn more about your mental illness and ways to overcome it. I built Ivy at IvyHacks, a hackathon hosted by the Ivy League universities, using IBM Watson Assistant. Then I developed a website using HTML and CSS that provides some statistics about mental illnesses to give users a better understanding of the widespread issue and know that they are not alone. Some helpful resources are also listed on the page. The Ivy chatbot on the website can help you with issues including depression, anxiety, stress, PTSD, addiction, ADHD, OCD, eating disorders, and suicidal thoughts. Based on your input, Ivy will send a response with information about your mental illness, resources such as support groups, and activity suggestions to better control your mental health. This project was my first time developing a chatbot and working with IBM Watson Assistant. It was also a great way for me to do critical research about mental illnesses and provide a safe space for people with mental illnesses to express their feelings and seek help.";

export const shortText = "Meet Ivy, a mental health chatbot to help users find information about mental illnesses, provide resources such as support groups, and suggest activities to better control their mental health...";

export const dates = "October 2020";

export const techUsed = "IBM Watson Assistant, HTML, CSS";

export const link = "https://github.com/AmyWeitzman/IvyHacks";