export const name = "Jeopardy";

export const longText = "A trivia buff and programming enthusiast whose goal is to one day be able to answer (or rather question) every clue on Jeopardy, I decided to spend one of my summers creating my own Jeopardy game. The design was based on the real Jeopardy TV show, including various categories, multiple rounds, and wagers. However, I also used my creativity to change certain aspects of the game to make it more unique and fun for my entire family. I began by writing the logic behind the game, such as modifying the score, changing the clues, and storing the players' information. One issue I faced was determining what data structures to use to store all the data, which was large and needed to be easily accessible quickly as to not interrupt the flow of the game. I spent much time optimizing the code to make sure that is was as concise and understandable as possible. Once the back-end worked, I made the game come to life by creating the front-end, which consisted of various windows that displayed the game board, the clues, and the rules. Prior to this project, I had no experience in creating GUIs in Java so I had to teach myself the Java Swing Library. After experimenting with the different features and determining the best ones to use for my project, I coded the program, fixing bugs here and there. Ultimately, the game turned out great and I am so proud of my accomplishments. Going in, I had no idea how to build the application, but since I was motivated, I was able to teach myself along the way. Throughout this process, I learned new computer science skills, enhanced my knowledge of programming and the software engineering process, and created a game that my family could play together.";

export const shortText = "A trivia buff and programming enthusiast whose goal is to one day be able to answer (or rather question) every clue on Jeopardy, I decided to spend one of my summers...";

export const dates = "Summer 2018";

export const techUsed = "Java, Java Swing";

export const link = ""